line-length = 120

[lint]
select = ["E", "F", "TID252"]
exclude = [
    "generated",
]

[lint.per-file-ignores]
"src/qiki/services/q_core_agent/core/*.py" = ["E402", "E501"]
"src/qiki/services/q_core_agent/main.py" = ["E402"]
"src/qiki/services/q_sim_service/*.py" = ["E402", "E501"]
"src/qiki/services/faststream_bridge/*.py" = ["E402", "E501"]
